Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -44,6 +44,12 @@ jobs:
 
       - run: |
           echo ${{ steps.regex-match.outputs.match }}
-          curl --user ${{ secrets.JIRA_TOKEN }} "https://certifyos.atlassian.net/rest/api/2/issue/${{ steps.regex-match.outputs.match }}?fields=status" | jq '.fields.status.name'
+          STATUS=$(curl --user ${{ secrets.JIRA_TOKEN }} "https://certifyos.atlassian.net/rest/api/2/issue/${{ steps.regex-match.outputs.match }}?fields=status" | jq '.fields.status.name')
+          if [[ $STATUS == "Done" ]]; then
+            echo "Done status"
+          else
+            echo "Status not done, failing"
+            exit 1
+          fi
         if: ${{ steps.regex-match.outputs.match != '' }}
           
